/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/cloud.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cloud({opacity, ...props}) {
  const { nodes} = useGLTF('./models/cloud.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cloudball001.geometry} >
        <meshStandardMaterial {...nodes.cloudball001.material} transparent opacity={opacity}/>
        </mesh>
    </group>
  )
}

useGLTF.preload('./models/cloud.glb')
