/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/cloud.glb 
*/

import React, {useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { fadeOnBeforeCompile } from '../utils/fadeMaterial'
import { useFrame } from '@react-three/fiber'

export default function Cloud({sceneOpacity, ...props}) {
  const { nodes} = useGLTF('./models/cloud.glb')
  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cloudball001.geometry} ref={materialRef}>
        <meshStandardMaterial onBeforeCompile={fadeOnBeforeCompile} envMapIntensity={2} transparent />
        </mesh>
    </group>
  )
}

useGLTF.preload('./models/cloud.glb')
